#Name of tflite model and label
model_file:  'detect.tflite'
labels_file: 'COCO_labels.txt'

#Minimum confidence 0 - 1 (0.25 good default value)
min_confidence: 0.5

#confidence bounds of 3d cluster
box_size: 0.8