#Path to tflite model
model_path: '/home/pi/catkin_ws/src/nimbus-perception/nimbus_pose/posenet_mobilenet_v1_100_257x257_multi_kpt_stripped.tflite'

#Minimum confidence -1.0 - 1.0
min_confidence: -1.0